### ISSUE TITLE
Is fuzzy matching supported?

### ISSUE THREAD

**Issue by daquexian** [prabirshrestha/asyncomplete-lsp.vim#11]
For example I have a object named `actual_result`, I'd like to just type `ar` to matching it. It is supported by ycm and feels very great.

**Comment by prabirshrestha** [comment]
not yet had to revert it due to some other bugs https://github.com/prabirshrestha/asyncomplete.vim/pull/49. will be working on it in the near future.

It is more of asyncomplete.vim issue and not asyncomplete-lsp.vim so feel free to file a bug there instead.

**Comment by prabirshrestha** [comment]
Here are few ones:

https://github.com/machakann/asyncomplete-ezfilter.vim
https://github.com/tsufeki/asyncomplete-fuzzy-match
