### ISSUE TITLE
[feature-request]Customize completion list abbr

### ISSUE THREAD

**Issue by yuin** [prabirshrestha/asyncomplete-lsp.vim#12]
Hi @prabirshrestha , I'm testing the asyncomplete & asyncomplete-lsp as replacements for each language plugins.

In completion, It works nicely with pyls under filetype=python.

![pyls](https://user-images.githubusercontent.com/56500/39681266-11631d1c-51e4-11e8-99f2-20014a6cf3e5.png)

But with go-langserver under filetype=go, It does not show function signatures.

![go-langserver](https://user-images.githubusercontent.com/56500/39681301-40adccd4-51e4-11e8-92a2-0731844d2e3a.jpg)

go-langserver set function sigunatures to `detail` key in an lsp response.  
`asyncomplete-lsp` uses `lsp#omni#get_vim_completion_item(v:val)` for converting lsp response items to vim completion items.

Since `lsp#omni#get_vim_completion_item(v:val)` does not use the `detail` at all, function signatures does not displayed.

It will be nice to have a way for customizing how to display items.

**Comment by prabirshrestha** [comment]
Merged in https://github.com/prabirshrestha/vim-lsp/pull/229
