### ISSUE TITLE
Auto-completion does not work in vim 8.1

### ISSUE THREAD

**Issue by kurdybacha** [prabirshrestha/asyncomplete-lsp.vim#13]
Same configuration works fine in neovim v0.2.2 but getting `Pattern not found` all the time in vim 8.1, Fedora 27, cquery compiled from master.

config:
```
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete-lsp.vim'

if executable('cquery')
   au User lsp_setup call lsp#register_server({
      \ 'name': 'cquery',
      \ 'cmd': {server_info->['cquery']},
      \ 'initialization_options': { 'cacheDirectory': '/tmp/cquery/cache' },
      \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp', 'cc'],
      \ })
endif
```

Debug log in vim-lsp shows correct list of suggestion for auto-completion.

**Comment by prabirshrestha** [comment]
Seems like related to this https://github.com/prabirshrestha/asyncomplete.vim/issues/59
Can you try setting this in your config? `set shortmess+=c`

**Comment by prabirshrestha** [comment]
Please upload the logs for both asyncomplete and vim-lsp.

**Comment by kurdybacha** [comment]
[asyncomplete.log](https://github.com/prabirshrestha/asyncomplete-lsp.vim/files/2322513/asyncomplete.log)
[vim-lsp.log](https://github.com/prabirshrestha/asyncomplete-lsp.vim/files/2322514/vim-lsp.log)

I was typing `std::vector`

**Comment by prabirshrestha** [comment]
Seems like the lang server is throwing some errors:

```
Mon 27 Aug 2018 06:36:40 AM IST:["<---(stderr)",1,"cquery",["(   0.012s) [querydb      ]        project.cc:69    | Failed to normalize /home/pawel/dotfiles/rtags/build/src/lua-prefix/src/lua-build","(   0.027s) [scan_includes]          utils.cc:192   | Unable to read file rc when reading directory /home/pawel/dotfiles/rtags/","(   0.027s) [scan_includes]          utils.cc:192   | Unable to read file rdm when reading directory /home/pawel/dotfiles/rtags/",""]]
```

I also do see completion working sometimes.

**Comment by prabirshrestha** [comment]
Please try updating to latest vim-lsp and asyncomplete. There were few fixes on path escaping that got merged in.
