### ISSUE TITLE
Does the completion work on multiple different filetypes?

### ISSUE THREAD

**Issue by ichitera** [prabirshrestha/asyncomplete-lsp.vim#15]
I wanted to use multiple language servers for multipe filetypes, but `asyncomplete-lsp` completed items of only one filetype where the `asyncomplete-lsp` was called at first. For example, if some items are completed on **a go buffer** at first, any items are  not completed on **a python buffer**, and vice versa.

Does the completion of `asyncomplete-lsp` work on only a single filetype in one Vim process?

In the following screencast, I demostrated the above example. Items were completed on a go buffer at first, and then I tried to complete items on a python buffer, but any items were completed.
![screencast](https://user-images.githubusercontent.com/31098747/50136752-1d59dd00-02dc-11e9-86e4-3e8c4d55573a.gif)
(I confirmed that omnifunc of`vim-lsp` worked on the both filetypes.)

The vimrc used in the above screencast:
```vimL
set nocompatible hidden laststatus=2
set splitbelow
set previewheight=2
language C

if !filereadable('plug.vim')
  silent !curl --insecure -fLo plug.vim
    \  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source plug.vim

call plug#begin('plugged')
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
call plug#end()

let g:lsp_log_verbose = 1
let g:lsp_log_file = './vim-lsp.log'
let g:asyncomplete_log_file = './asyncomplete.log'
imap <c-space> <Plug>(asyncomplete_force_refresh)

if executable('go-langserver')
    " go get -u sourcegraph/go-langserver
    au User lsp_setup call lsp#register_server({
        \ 'name': 'go-langserver',
        \ 'cmd': {server_info->['go-langserver', '-gocodecompletion']},
        \ 'whitelist': ['go'],
        \ })
    au FileType go setlocal omnifunc=lsp#complete
endif
if executable('pyls')
    " pip install python-language-server
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->['pyls']},
        \ 'whitelist': ['python'],
        \ })
    au FileType python setlocal omnifunc=lsp#complete
endif
```

The logs obtained in the above screencast are below.

- [vim-lsp.log](https://github.com/prabirshrestha/asyncomplete-lsp.vim/files/2689195/vim-lsp.log)
- [asyncomplete.log](https://github.com/prabirshrestha/asyncomplete-lsp.vim/files/2689196/asyncomplete.log)

**Environment:**
- OS: Windows 10 64bit
- Vim: 8.1.606
- Python: 3.7.0
- python-language-server: 0.21.4
- go-langserver: v3-dev

**Comment by prabirshrestha** [comment]
Can you try this PR instead. https://github.com/prabirshrestha/asyncomplete-lsp.vim/pull/22

**Comment by prabirshrestha** [comment]
I sent a new PR. Could you try this instead. https://github.com/prabirshrestha/asyncomplete-lsp.vim/pull/23

**Comment by ichitera** [comment]
I confirmed that this issue was fixed.
Thank you.

**Comment by prabirshrestha** [comment]
Merged. Thanks for confirming.
