### ISSUE TITLE
Clangd completion list offers header identifiers first

### ISSUE THREAD

**Issue by frdeso** [prabirshrestha/asyncomplete-lsp.vim#18]
When autocompleting words in C, I often get weird completion suggestions. I am not quite sure what plugin is causing this.
Here is the symptom: ![](https://i.imgur.com/IEefz5D.png)

In this tiny C file please note that I include the <inttypes.h> header file.
When trying to autocomplete "pr" to "previous" defined on the previous line I get a bunch of other identifiers (from inttypes.h) before the one defined in the current file.

asyncomplete.log: https://gist.github.com/frdeso/b6b4059e8a25e4fb347e373e6e477b7e
vim-lsp.log: https://gist.github.com/frdeso/d49d3e5ad8ac51645c9641d520b0227e
minimal vimrc: https://gist.github.com/frdeso/f2ecebaab856193d1850c3bdc8bafe05

Looking at the vim-lsp.log file at line [305](https://gist.github.com/frdeso/d49d3e5ad8ac51645c9641d520b0227e#file-vim-lsp-log-L305) the clangd reply seems to be in the right ordering.

Is a way to prioritize the matches from the current file/project?

**Comment by prabirshrestha** [comment]
Could you try the v2 branch.

**Comment by frdeso** [comment]
Using the v2 branch of the [asyncomplete](https://github.com/prabirshrestha/asyncomplete.vim) project fixes it. Thank you!

**Comment by prabirshrestha** [comment]
Great. Closing it for now since I plan to merge v2 to master this week.
