### ISSUE TITLE
LSP completion breaks after first error in flow

### ISSUE THREAD

**Issue by electric-ladyland** [prabirshrestha/asyncomplete-lsp.vim#19]
Hopefully you can help me debug this. I'm using a vim config that worked on a previous Arch system, so I think the problem lies in the version of something that changed when I switched Arch systems.

If I open a JS file with flow enabled, initially completion includes LSP candidates (everything works well).
Then I create an error of some kind, e.g. reference a variable that does not exist. Then I remove the error.
After that, asyncomplete does not show any LSP candidates until I restart vim.

[asyncomplete.log](https://gist.github.com/electric-ladyland/3b27f0788da611ca555555a66e3e873b)
[vim-lsp.log](https://gist.github.com/electric-ladyland/8a881fdfd0139b0d1e5da01a4d9aefd8)

These log files show the process of first checking LSP completion works, then typing a variable 'xxx' to cause a flow error, then removing it, and checking that LSP completion stops working.

As mentioned this used to work fine with the same vim config, so I have not created a minimal vim config to reproduce it (unless you think it's necessary). Anything jump out from the log files?

[This](https://github.com/electric-ladyland/.dotfiles/blob/master/vim/vimrc#L506) shows my lsp config.
[This](https://github.com/electric-ladyland/.dotfiles/blob/master/vim/vimrc#L586) shows my asyncomplete config.

BTW - thank you so much for this set of plugins you have created. I want to donate...

**Comment by prabirshrestha** [comment]
Please try asyncomplete v2 branch.

**Comment by electric-ladyland** [comment]
I don't get any LSP completions in v2 branch.

**Comment by electric-ladyland** [comment]
Also observed that in the master asyncomplete branch, the original error I reported does not happen with TypeScript (LSP completion works always). So it's flow LSP specific. I'm going to try to figure out what could have changed to cause this, but flow LSP completion is now way more fragile than it was a few days ago for me.

**Comment by prabirshrestha** [comment]
Closing since it is a bug on server.

**Comment by electric-ladyland** [comment]
Server as in the Flow package or the vim-lsp plugin? I can recreate the issue where you want and provide more extensive info...

**Comment by electric-ladyland** [comment]
Just downgraded to flow-bin 0.93 from 0.94, confirmed LSP completion works properly now. Do you have any info I can use to file an issue in the flow-bin repo? I don't know how to technically describe the issue, or if it's even an issue at all...

**Comment by prabirshrestha** [comment]
vimlsp and asyncomplete logs should be good enough. Feel free to ping me in their issue if you need help from my side.

**Comment by electric-ladyland** [comment]
Created https://github.com/flowtype/flow-bin/issues/151
