### ISSUE TITLE
The popup menu does not open when a buffer is modified soon after the buffer opens

### ISSUE THREAD

**Issue by ichitera** [prabirshrestha/asyncomplete-lsp.vim#24]
The popup menu does not open when a buffer is modified soon after the buffer opens. Current `asyncomplete-lsp.vim` seems to require some pauses before buffers are edited.

When I modified a buffer soon after the buffer opens, the popup menu did not open as follows:
![A buffer was modified soon after the buffer opens](https://user-images.githubusercontent.com/31098747/55852402-d0a25680-5b97-11e9-9d05-f49c419465d3.gif)
In the above screencast, I typed `<c-space>` to execute `<Plug>(asyncomplete_force_refresh)`, but the popup menu did not open, and any item was not completed. After that, I typed `<c-x><c-o>` to execute `omnifunc`, and `omnifunc` worked expectedly.

If I waited a while before modified a buffer, the popup menu expectedly opened as follows:
![A buffer was modified in a while after the buffer opens](https://user-images.githubusercontent.com/31098747/55852413-e0219f80-5b97-11e9-9213-0260da737a9f.gif)
In the above screencast, I waited a while before I typed any key, and I typed `<c-space>` to execute `<Plug>(asyncomplete_force_refresh)`, and the popup menu expectedly opened. `omnifunc` also worked expectedly.

These are logs obtained in the above screencasts:
- When  buffer was modified soon after the buffer opens:
   - [asyncomplete.log](https://github.com/prabirshrestha/asyncomplete-lsp.vim/files/3062077/asyncomplete.log)
   - [vim-lsp.log](https://github.com/prabirshrestha/asyncomplete-lsp.vim/files/3062078/vim-lsp.log)

- When a buffer was modified in a while after the buffer opens
   - [asyncomplete.log](https://github.com/prabirshrestha/asyncomplete-lsp.vim/files/3062080/asyncomplete.log)
   - [vim-lsp.log](https://github.com/prabirshrestha/asyncomplete-lsp.vim/files/3062079/vim-lsp.log)

This is the vimrc that I used in the above screencast:
```VimL
language C

" for vim-plug
source plug.vim

call plug#begin('plugged')
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
call plug#end()

let g:lsp_log_verbose = 1
let g:lsp_log_file = './vim-lsp.log'
let g:asyncomplete_log_file = './asyncomplete.log'
imap <c-space> <Plug>(asyncomplete_force_refresh)

if executable('pyls')
    " pip install python-language-server
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->['pyls']},
        \ 'whitelist': ['python'],
        \ })
    au FileType python setlocal omnifunc=lsp#complete
endif
````

**Environment:**
- OS: Windows 10 64bit
- Vim: 8.1.1142
- async.vim: [f30145](https://github.com/prabirshrestha/async.vim/tree/f3014550d7a799097e56b094104dd2cd66cf2612)
- asyncomplete.vim: [f4a5b8](https://github.com/prabirshrestha/asyncomplete.vim/tree/f4a5b881c86e8a6a7701db023c0631417851815d)
- asyncomplete-lsp.vim [05389e](https://github.com/prabirshrestha/asyncomplete-lsp.vim/tree/05389e93a81aa4262355452ebdac66ae2a1939fb)
- vim-lsp: [a79fb04](https://github.com/prabirshrestha/vim-lsp/tree/a79fb04d36e89261e356c16e638bbee284e42d4a)

- Python: 3.7.3
- python-language-server: 0.26.1

**Comment by mattn** [comment]
Language Server is external daemon program. And it may take few seconds to ready to accept requests.

**Comment by ichitera** [comment]
Thank you for the comment.
I think it is reasonable that it takes a few seconds to receive completion items from the language server program and show the items in the popup menu.
I expected that completion items were shown in the popup menu a few seconds after I wrote code, but `asyncomplete-lsp.vim` never opened the popup menu even though completion items from omnifunc provided by `vim-lsp` were available.

I will add more explanation about the issue.

**Current Behavior (the first screencast):**

Completion items were never shown by `asyncomplete-lsp.vim` also after some signs were shown by `vim-lsp`. (I thought that the completion items were also received from the server when the signs appeared.)

1. open a python file (which includes text "import sys\n")
2. type `sys.` in the insert mode
3. (signs are appear in a window, and completion items may be received)
4. type `<C-Space>` to refresh the popup
5. (but any completion item never appears even though I repeat 4) <---- diff

**Expected Behavior:**

Completion items are shown by `asyncomplete-lsp.vim` after completion items become available.

1. open a python file (which includes text "import sys\n")
2. type `sys.` in the insert mode
3. (signs are appear in a window, and completion items may be received)
4. type `<C-Space>` to refresh the popup menu
5. (completion items appear in the popup menu) <---- diff

----
**Current Behavior that Works Expectedly (the second screencast)**

Completion items were shown by `asyncomplete-lsp.vim`, when I waited to write code until some signs were shown.

1. open a python file (which includes text "import sys\n")
2. (signs are appear in a window, and completion items may be received) <---- diff
3. type `sys.` in the insert mode <---- diff
4. type `<C-Space>` to refresh the popup
5. (completion items appear in the popup menu) <---- diff

**Comment by ichitera** [comment]
I will close this issue because this issue is solved by https://github.com/prabirshrestha/asyncomplete.vim/pull/147.
