### ISSUE TITLE
Python types (PEP 484) support

### ISSUE THREAD

**Issue by GoldsteinE** [prabirshrestha/asyncomplete-lsp.vim#25]
I'm not sure where to put this issue, please guide me to another repo is needed.
It'd be cool if autocompletion popup showed Python type annotations in function signature.
![image](https://user-images.githubusercontent.com/12019211/61597163-98d69080-ac15-11e9-8587-8e4e4ce4d92d.png)

**Comment by GoldsteinE** [comment]
Seems like Python types are present in info:
`["core","asyncomplete#preprocess_complete calling complete()",3[{"word":"test","menu":"__main__.A","empty":1,"info":"test(self, a: int) -> str","kind":"function","abbr":"test(a)","icase":1,"dup":1}]]`
My `completeopt` is `menuone,preview`.

**Comment by prabirshrestha** [comment]
Please try latest master gain. There has been some improvements over signature help.
