### ISSUE TITLE
E716: Key not present in Dictionary: kind

### ISSUE THREAD

**Issue by renstrom** [prabirshrestha/asyncomplete-lsp.vim#3]
Hi. I'm trying to use this together with https://github.com/sourcegraph/javascript-typescript-langserver (and [prabirshrestha/asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim)) but run into the following error when it wants to complete:

```
Error detected while processing function <SNR>119_on_stdout[4]..<SNR>118__on_lsp_stdout[50]..<lambda>8[1]..<
SNR>30_handle_completion:
E716: Key not present in Dictionary: kind
```

And it seems the culprit is this line. It wants to access they key `kind`, but I guess the LSP server isn't returning that key for some of the items.

```vim
let l:matches = map(l:items,'{"word":v:val["label"],"dup":1,"icase":1,"menu": s:get_symbol_text_from_kind(v:val["kind"])}')
```

Now, I'm not familiar with the LSP spec. So I don't really know if the server is returning incorrect result (i.e. skipping the `kind` key) or if asyncomplete-lsp.vim is a bit too optimistic if what keys are present.

**Comment by prabirshrestha** [comment]
This should now be fixed. Thanks for reporting the bug.
